### ISSUE TITLE
Mapfile: after applying patch #58 duplicated namespaces in tinyows --check

### ISSUE THREAD

**Issue by jewie** [MapServer/tinyows#72]
After applying patch #58 (@pka) the buffer problem is solved, but duplicated namespaces occur in tinyows --check (Available layers) and furthermore in response documents of wfs_get_capabilities.c,  wfs_describe.c and wfs_get_feature.c:

Available layers:
- schema.tablename (srid) -> ns_prefix:ns_prefix:layer_name

**Comment by jmckenna** [comment]
This seems to be fixed earlier through this commit f4345f8  
Closing.
