### ISSUE TITLE
openlayers3 mapserver 

### ISSUE THREAD

**Issue by hosein021555** [mapserver/tinyows#89]
i'd like to create mapserver with openlayer3  and the below code isn't show 
some one has solution 

mapfile 

MAP
  DEFRESOLUTION 96
  EXTENT 530076.378119036 3955633.12330454 535309.119388271 3958672.31583408
  FONTSET "C:\\Program Files (x86)\\MapManager\\templates\\font.list"
  IMAGETYPE "png24"
  NAME "MS"
  RESOLUTION 96
  SHAPEPATH ""
  SIZE 1022 594
  STATUS ON
  SYMBOLSET "C:\\Program Files (x86)\\MapManager\\templates\\symbols.sym"
  UNITS METERS

  OUTPUTFORMAT
    NAME "png24"
    MIMETYPE "image/png"
    DRIVER "AGG/PNG"
    EXTENSION "png"
    IMAGEMODE RGB
    TRANSPARENT FALSE
  END # OUTPUTFORMAT

  OUTPUTFORMAT
    NAME "print"
    MIMETYPE "image/png"
    DRIVER "AGG/PNG"
    EXTENSION "png"
    IMAGEMODE RGB
    TRANSPARENT FALSE
  END # OUTPUTFORMAT

  PROJECTION
    "proj=utm"
    "zone=39"
    "datum=WGS84"
    "units=m"
    "no_defs"
  END # PROJECTION
  LEGEND
    KEYSIZE 20 10
    KEYSPACING 5 5
    LABEL
      SIZE MEDIUM
      OFFSET 0 0
      SHADOWSIZE 1 1
      TYPE BITMAP
    END # LABEL
    STATUS OFF
  END # LEGEND

  QUERYMAP
    SIZE -1 -1
    STATUS OFF
    STYLE HILITE
  END # QUERYMAP

  SCALEBAR
    INTERVALS 4
    LABEL
      SIZE MEDIUM
      OFFSET 0 0
      SHADOWSIZE 1 1
      TYPE BITMAP
    END # LABEL
    SIZE 200 3
    STATUS OFF
    UNITS MILES
  END # SCALEBAR

  WEB
    METADATA
      "distance_units"	"MS_METERS"
      "mapmanager_version"	"1.0.0.0"
      "coordsys_name"	"WGS 84 / UTM zone 39N"
    END # METADATA
  END # WEB

  LAYER
    CONNECTION "host=localhost   dbname=network  user=postgres  password=021555  port=5432"
    CONNECTIONTYPE POSTGIS
    DATA "geom from tehran"
    METADATA
      "coordsys_name"	"WGS 84 / UTM zone 39N"
    END # METADATA
    NAME "tehran"
    PROJECTION
      "proj=utm"
      "zone=39"
      "datum=WGS84"
      "units=m"
      "no_defs"
    END # PROJECTION
    STATUS ON
    TEMPLATE "query"
    TILEITEM "location"
    TYPE LINE
    UNITS METERS
    CLASS
      NAME "Class (0)"
      LABEL
        FONT "arial"
        SIZE 8
        OFFSET 0 0
        POSITION CC
        SHADOWSIZE 1 1
        TYPE TRUETYPE
      END # LABEL
      STYLE
        COLOR 0 128 64
        SIZE 8
      END # STYLE
    END # CLASS
  END # LAYER

END # MAP

<!doctype html>
<html lang="en">
  <head>
    <link rel="stylesheet" href="http://openlayers.org/en/v3.15.1/css/ol.css" type="text/css">
    <style>
      .map {
        height: 100%;
        width: 100%;
      }
    </style>
    <script src="http://openlayers.org/en/v3.15.1/build/ol.js" type="text/javascript"></script>
    <title>web gis</title>
  </head>
  <body>
  
    <div id="map"></div>
    <script type="text/javascript">
     
    var extent = [530076.378119036 ,3955633.12330454 ,535309.119388271 ,3958672.31583408];
    var layers = [
          new ol.layer.Image({
              extent: extent,
              source: new ol.source.ImageWMS({
              url: "http://localhost/cgi-bin/mapserv.exe?map=C:/ms4w/Apache/htdocs/ol/tehran.map&",
              params: {
                'LAYERS': 'tehran',
                'CRS': 'EPSG:32639'
              },
              serverType: 'mapserver'
              })
          })
        ];
       
    
    
    var projection = new ol.proj.Projection({
     code: 'EPSG:32639',
     units: 'm'
     });
            var  view = new ol.View({
            center: [532416 ,3957232],
            extent: extent,
            zoom: 15,
            projection: projection
              });
         
   
    
        var map = new ol.Map({
          layers: layers,
          view: view,
          target: 'map',
          controls: ol.control.defaults().extend([
           new ol.control.ScaleLine(),
           new ol.control.MousePosition()
          ])
           });
    </script>
  </body>
</html>

**Comment by tomkralidis** [comment]
Please post questions to the [mapserver-users](https://lists.osgeo.org/mailman/listinfo/mapserver-users) mailing list.  MapServer's GitHub issues are for software bugs/enhancements and related tasks.
