### ISSUE TITLE
Could not run TinyOWS

### ISSUE THREAD

**Issue by louptheron** [MapServer/tinyows#92]
Hi,

When I try to execute TinyOWS with a PostGIS database (`timescale/timescaledb-postgis:1.7.4-pg11`) I got this error:
```
row number 0 is out of range 0..-1
Segmentation fault (core dumped)
```

Any idea ?

Thank you

**Comment by jmckenna** [comment]
I will do some testing on PG 13/PostGIS 3 and get back to you...

**Comment by louptheron** [comment]
Thank you, I got the same result with `timescale/timescaledb-postgis:1.7.0-pg9.6`.

Btw, could TinyOWS be used in production for WFS-T w/ Openlayers ? Is it maintained ? 
I really like the configuration approach, unlike the Geoserver "mouse-click" one...

Thank you,

**Comment by jmckenna** [comment]
background: TinyOSW is included (and tested) for every MS4W release (on Windows) and I know of several MS4W production instances running TinyOWS.

While I get setup, could you also test with PG13/PostGIS 3 ?  thanks.

**Comment by louptheron** [comment]
I tested with PG 12 / PostGIS 2.5.5, with the same error.

What make you think it should work the upper versions ? TinyOWs seems linked with libs targeting PostgreSQL 8.x and 9.x.

Thanks,

**Comment by jmckenna** [comment]
Tested successfully with PG 13 / PostGIS 3.0.2.

However I did discover a problem in my testing, with the demo application is using HTTPS.  Will have to file a new ticket for that.

**Comment by louptheron** [comment]
Interesting, thank you for the feedback !
